import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { SpeedInsights } from "@vercel/speed-insights/next";
import BlogSidebar from "@/components/BlogSidebar";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export const revalidate = 300;

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full h-screen overflow-hidden flex flex-col bg-gray-50">
        <div className="flex-1 flex overflow-hidden">
          {/* Main content area */}
          <main className="flex-1 overflow-y-auto">{children}</main>
          {/* Sidebar */}
          <BlogSidebar />
        </div>
        <SpeedInsights />
      </body>
    </html>
  );
}
